### ISSUE TITLE
Contact not getting created 

### ISSUE THREAD

**Issue by lddd** [mnkgrover08/whatsapp_automation#12]
Hello there,

i am trying to add a contact like seen in the video example. But contacts stay empty. 

Here´s my output:

```
 ... entered into whatsapp
+49 170 12345678
Search Click icon button not Found
Successfully Processed
49 170 12345678
ok

----------------------------------------------------------------------
Ran 1 test in 8.973s

OK
de-entetred
 [x] Received {'emulator_name': 'pixel_1', 'mobile_number': '+49 170 12345678'}
```
Any idea?

**Comment by mnkgrover08** [comment]
Hey Roman

output shows that program is not able to add contact because it can not
find the search button in your contacts app. which is part of the logic.

please check your android version and Google Contacts APP version. and make
sure they both are matching as specified in github project.

please note that code is using xpath logic for picking elements in Android
app. so version compatibility is very important. Maybe the Google Contacts
app which you are using may not have search button due to which error is
coming.

Regards
Mayank

**Comment by lddd** [comment]
Ok thanks for letting me know, you might want to tell me what android / google contacts app version was used in your example.
